In [1]:
!pip install gensim -q
import gensim.downloader as api

   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 27.9/27.9 MB 92.3 MB/s eta 0:00:00

In [9]:
model = api.load("word2vec-google-news-300")

print("Model loaded ✅")
print("Vocab size:", len(model.key_to_index))
print("Vector size:", model.vector_size)

Model loaded ✅
Vocab size: 3000000
Vector size: 300

In [10]:
# Inspect Single Word Vectors
vec_book = model["book"]
print("Vector shape:", vec_book.shape)
print("First 10 components:", vec_book[:10])

Vector shape: (300,)
First 10 components: [ 0.11279297 -0.02612305 -0.04492188  0.06982422  0.140625    0.03039551
 -0.04370117  0.24511719  0.08740234 -0.05053711]

In [12]:
 #Finding Most Similar Words
for w in ["book", "apple", "university", "king", "beautiful"]:
  print(f"\nTop 5 similar words to '{w}':")
  for word, score in model.most_similar(w, topn=5):
    print(f"  {word:<15}  {score:.3f}")

Top 5 similar words to 'book':
  tome             0.749
  books            0.738
  memoir           0.730
  paperback_edition  0.687
  autobiography    0.674

Top 5 similar words to 'apple':
  apples           0.720
  pear             0.645
  fruit            0.641
  berry            0.630
  pears            0.613

Top 5 similar words to 'university':
  universities     0.700
  faculty          0.678
  unversity        0.676
  undergraduate    0.659
  univeristy       0.659

Top 5 similar words to 'king':
  kings            0.714
  queen            0.651
  monarch          0.641
  crown_prince     0.620
  prince           0.616

Top 5 similar words to 'beautiful':
  gorgeous         0.835
  lovely           0.811
  stunningly_beautiful  0.733
  breathtakingly_beautiful  0.723
  wonderful        0.685

In [23]:
#Word Analogies
result = model.most_similar(
    positive=["king", "woman"],
    negative=["man"],
    topn=5
)

print("Analogy: king - man + woman ≈ ?")
for word, score in result:
    print(f"{word:<15} {score:.3f}")

print("-"*50)

coun_res = model.most_similar(
    positive=["paris", "italy"],
    negative=["france"],
    topn=5
)
print("paris - france + italy ≈ ?")
for word, score in coun_res:
    print(f"{word:<15} {score:.3f}")

print("-"*50)

wo_res = model.most_similar(
    positive=["walking", "swim"],
    negative=["walk"],
    topn=5
)
print("walking - walk + swim ≈ ?")
for word, score in wo_res:
    print(f"{word:<15} {score:.3f}")

print("-"*50)

siz_res = model.most_similar(
    positive=["big", "bigger"],
    negative=["smaller"],
    topn=5
)
print("big - bigger + smaller ≈ ?")
for word, score in siz_res:
    print(f"{word:<15} {score:.3f}")

Analogy: king - man + woman ≈ ?
queen           0.712
monarch         0.619
princess        0.590
crown_prince    0.550
prince          0.538
--------------------------------------------------
paris - france + italy ≈ ?
lohan           0.507
madrid          0.482
heidi           0.480
real_madrid     0.475
florence        0.468
--------------------------------------------------
walking - walk + swim ≈ ?
swimming        0.825
swam            0.681
swims           0.654
swimmers        0.649
paddling        0.642
--------------------------------------------------
big - bigger + smaller ≈ ?
huge            0.696
biggest         0.607
abig            0.538
HUGE            0.531
great           0.512

In [24]:
#Cosine Similarity Between Words
pairs = [
    ("apple", "banana"),
    ("apple", "cat"),
    ("cat", "dog"),
    ("king", "queen"),
    ("man", "woman")
]

for w1, w2 in pairs:
    sim = model.similarity(w1, w2)
    print(f"similarity({w1:>8}, {w2:<8}) = {sim:.3f}")

similarity(   apple, banana  ) = 0.532
similarity(   apple, cat     ) = 0.207
similarity(     cat, dog     ) = 0.761
similarity(    king, queen   ) = 0.651
similarity(     man, woman   ) = 0.766

In [28]:
#Similarity Matrix for a Set of Words
import numpy as np
import pandas as pd

words = ["king", "queen", "man", "woman", "prince", "princess"]

# Build similarity matrix
sim_matrix = np.zeros((len(words), len(words)))

for i, w1 in enumerate(words):
    for j, w2 in enumerate(words):
        sim_matrix[i, j] = model.similarity(w1, w2)

sim_df = pd.DataFrame(sim_matrix, index=words, columns=words)
sim_df

              king     queen       man     woman    prince  princess
king      1.000000  0.651096  0.229427  0.128480  0.615999  0.516200
queen     0.651096  1.000000  0.166582  0.316181  0.553409  0.707053
man       0.229427  0.166582  1.000000  0.766401  0.281022  0.250599
woman     0.128480  0.316181  0.766401  1.000000  0.269894  0.398338
prince    0.615999  0.553409  0.281022  0.269894  1.000000  0.698651
princess  0.516200  0.707053  0.250599  0.398338  0.698651  1.000000

In [32]:
# practic
list1 = ["apple", "banana", "orange", "cat", "dog", "car"]
sim_matrix1 = np.zeros((len(list1), len(list1)))

for i, w1 in enumerate(list1):
    for j, w2 in enumerate(list1):
        sim_matrix1[i, j] = model.similarity(w1, w2)

sim_df1 = pd.DataFrame(sim_matrix1, index=list1, columns=list1)
sim_df1

           apple    banana    orange       cat       dog       car
apple   1.000000  0.531841  0.392035  0.207491  0.219697  0.128307
banana  0.531841  1.000000  0.368210  0.230720  0.185833  0.112259
orange  0.392035  0.368210  1.000000  0.136308  0.118585  0.061496
cat     0.207491  0.230720  0.136308  1.000000  0.760946  0.215282
dog     0.219697  0.185833  0.118585  0.760946  1.000000  0.310002
car     0.128307  0.112259  0.061496  0.215282  0.310002  1.000000

In [33]:
country = ["paris", "france", "berlin", "germany", "rome", "italy"]
sim_matrix2 = np.zeros((len(country), len(country)))
for i, w1 in enumerate(country):
    for j, w2 in enumerate(country):
        sim_matrix2[i, j] = model.similarity(w1, w2)

sim_df2 = pd.DataFrame(sim_matrix1, index=country, columns=country)
sim_df2

            paris    france    berlin   germany      rome     italy
paris    1.000000  0.531841  0.392035  0.207491  0.219697  0.128307
france   0.531841  1.000000  0.368210  0.230720  0.185833  0.112259
berlin   0.392035  0.368210  1.000000  0.136308  0.118585  0.061496
germany  0.207491  0.230720  0.136308  1.000000  0.760946  0.215282
rome     0.219697  0.185833  0.118585  0.760946  1.000000  0.310002
italy    0.128307  0.112259  0.061496  0.215282  0.310002  1.000000

In [34]:
# Filtering Vocabulary by Prefix
prefix = "covid"

vocab = sorted([
    w for w in model.key_to_index.keys()
    if w.lower().startswith(prefix)
])

print(f"Found {len(vocab)} words starting with '{prefix}':")
print(vocab[:50])

Found 15 words starting with 'covid':
['COVIDIEN', 'Covidien', 'Covidien_COV', 'Covidien_Imaging', 'Covidien_Ltd.', 'Covidien_Ltd_COV.N', 'Covidien_Mallinckrodt', 'Covidien_NYSE_COV', 'Covidien_Optimark', 'Covidien_PLC', 'Covidien_Plc', 'Covidien_manufactures_distributes', 'Covidien_plc', 'Covidien_plc_COV', 'Covidien_plc_NYSE_COV']

In [35]:
#Handling Out-of-Vocabulary (OOV) Words
def safe_most_similar(word, topn=5):
    if word in model.key_to_index:
        return model.most_similar(word, topn=topn)
    else:
        print(f"'{word}' is OOV (not in vocabulary).")
        return []

safe_most_similar("Alexis")
safe_most_similar("Iran")

[('Tehran', 0.8340339064598083),
 ('Iranian', 0.8208497166633606),
 ('Islamic_republic', 0.8135175108909607),
 ('Islamic_Republic', 0.805050253868103),
 ('Iranians', 0.7819221615791321)]

In [38]:
#Fuzzy Matching
from difflib import get_close_matches

def suggest_similar_spelling(word, n=5, cutoff=0.7):
    candidates = get_close_matches(word, model.key_to_index.keys(), n=n, cutoff=cutoff)
    print(f"Closest matches to '{word}':", candidates)

suggest_similar_spelling("Alexis")
suggest_similar_spelling("Germani")

Closest matches to 'Alexis': ['Alexis', 'Alexxis', 'Alexsis', 'Alexius', 'Alexios']
Closest matches to 'Germani': ['Germani', 'Germanis', 'Germanic', 'Germania', 'German']

In [39]:
import numpy as np

# get list of vocab words
vocab_list = list(model.key_to_index.keys())

# sample 5 random words
np.random.seed(42)
random_words = np.random.choice(vocab_list, 5)
print("Random words:", random_words)

for w in random_words:
    print(f"\nNeighbors of '{w}':")
    try:
        for word, score in model.most_similar(w, topn=5):
            print(f"  {word:<15} {score:.3f}")
    except KeyError:
        print("  (Not in vocab)")

Random words: ['Representative_Porter_Goss' 'frontbencher_Christopher_Pyne'
 'Eminent_scholars' 'IN_SUPPORTING' 'Abbeybraney']

Neighbors of 'Representative_Porter_Goss':
  Congressman_Porter_Goss 0.735
  Rep._Porter_Goss 0.673
  Porter_Goss_R-Fla. 0.635
  Porter_Goss_R_Fla 0.612
  Ted_Deutch_D    0.586

Neighbors of 'frontbencher_Christopher_Pyne':
  frontbencher_Anthony_Albanese 0.631
  independent_Bob_Katter 0.612
  Meg_Lees        0.594
  Labor_frontbencher_Anthony_Albanese 0.592
  senator_Judith_Troeth 0.591

Neighbors of 'Eminent_scholars':
  scholars_academicians 0.704
  academicians_intellectuals 0.660
  intellectuals_academicians 0.660
  academicians    0.630
  thinkers_philosophers 0.618

Neighbors of 'IN_SUPPORTING':
  WELCOMED_THE    0.881
  TO_STRENGTHEN   0.876
  SAID_THAT_THE   0.875
  BAHRAINS        0.874
  TO_BAHRAIN      0.871

Neighbors of 'Abbeybraney':
  Shotgun_Willy   0.656
  Clowance        0.654
  Akilak          0.641
  Venn_Ottery     0.640
  I'msingingtheblues 0.639